# Generated by Django 3.0.6 on 2020-06-01 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BugTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(max_length=30)),
                ('bug_description', models.TextField()),
                ('status', models.CharField(choices=[('O', 'Open'), ('IP', 'In-Progress'), ('C', 'Closed')], default=('O', 'Open'), max_length=2)),
                ('date_created', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtrack.Project')),
            ],
        ),
    ]
