# Generated by Django 3.0.6 on 2020-06-03 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugticket',
            options={'permissions': [('view_form', 'Can view BugTicket form')]},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_form', 'Can view Project form')]},
        ),
        migrations.AlterField(
            model_name='bugticket',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
